"""empty message

Revision ID: 188ea38e2bad
Revises: 5a1fdac96b77
Create Date: 2021-12-27 22:19:29.107046

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "188ea38e2bad"
down_revision = "5a1fdac96b77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.String(length=100), nullable=False),
        sa.Column("transfer_id", sa.String(length=100), nullable=False),
        sa.Column("target_account_id", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "create_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("complaint_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
