"""empty message

Revision ID: 87e4b671c8eb
Revises: 5368e78198b6
Create Date: 2022-01-03 21:05:09.976107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87e4b671c8eb"
down_revision = "5368e78198b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "administrators", ["username"])
    op.drop_index("users_username_uindex", table_name="users")
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_index("users_username_uindex", "users", ["username"], unique=False)
    op.drop_constraint(None, "administrators", type_="unique")
    # ### end Alembic commands ###
