"""empty message

Revision ID: e184e95c2442
Revises: 87e4b671c8eb
Create Date: 2022-01-03 21:26:06.324836

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e184e95c2442"
down_revision = "87e4b671c8eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=False),
        sa.Column("interior_color", sa.String(length=32), nullable=False),
        sa.Column("tampo", sa.String(length=32), nullable=False),
        sa.Column("photo_url", sa.String(length=255), nullable=False),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_pk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_pk"],
            ["users.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cars")
    # ### end Alembic commands ###
